const STORAGE_KEY="study-room-attendance-v1";
const DEFAULT_PERIODS=[{key:"period8",label:"8교시"},{key:"night1",label:"야자1교시"},{key:"night2",label:"야자2교시"}];
const $=id=>document.getElementById(id);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const thisMonth=()=>today().slice(0,7);
const clone=x=>JSON.parse(JSON.stringify(x));
const uuid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2);
function blankState(){return{teacherName:"정독실 담당교사",autoAbsenceOnApproval:true,attendanceMode:"separate",periods:clone(DEFAULT_PERIODS),activeWeekdays:[1,2,3,4,5],excludedWeekdays:[0,6],students:[],monthlyStudents:{},monthlyStudentMeta:{},monthlyConfigs:{},attendanceRecords:{},absenceRequests:[]}}
function load(){const s=readSharedStateSync(STORAGE_KEY);return Object.assign(blankState(),s||{}, {students:Array.isArray(s?.students)?s.students:[],monthlyStudents:s?.monthlyStudents||{},monthlyStudentMeta:s?.monthlyStudentMeta||{},monthlyConfigs:s?.monthlyConfigs||{},attendanceRecords:s?.attendanceRecords||{},absenceRequests:s?.absenceRequests||[],periods:Array.isArray(s?.periods)&&s.periods.length?s.periods:clone(DEFAULT_PERIODS)})}
let state=load(),selectedStudentId=null;
function save(){writeSharedStateSync(STORAGE_KEY,state)}
function studentsFor(month){if(Object.prototype.hasOwnProperty.call(state.monthlyStudents,month))return clone(state.monthlyStudents[month]||[]).sort((a,b)=>a.seatNumber-b.seatNumber);return clone(state.students||[]).sort((a,b)=>a.seatNumber-b.seatNumber)}
function allStudents(){const m=new Map;(state.students||[]).forEach(s=>m.set(s.id,s));Object.values(state.monthlyStudents||{}).flat().forEach(s=>m.set(s.id,s));return [...m.values()]}
function student(id,month){return studentsFor(month||thisMonth()).find(s=>s.id===id)||allStudents().find(s=>s.id===id)}
function periods(){return state.periods?.length?state.periods:DEFAULT_PERIODS}
function fmtDate(d){const x=new Date(d+"T00:00:00");return new Intl.DateTimeFormat("ko-KR",{month:"long",day:"numeric",weekday:"short"}).format(x)}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function statusMap(record,id){const cur=record?.periodStatuses?.[id]||{};const out={};periods().forEach(p=>out[p.key]=cur[p.key]||"present");return out}
function isAbsent(v){return v==="manual_absent"||v==="approved_absent"}
function monthAbsence(month,id){return Object.values(state.attendanceRecords[month]||{}).reduce((n,r)=>n+Object.values(statusMap(r,id)).filter(isAbsent).length,0)}
function monthParticipation(month,id){const dates=Object.values(state.attendanceRecords[month]||{});return dates.reduce((n,r)=>n+Object.values(statusMap(r,id)).filter(v=>v==="present").length,0)}
document.querySelectorAll(".nav-btn[data-view]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(b.dataset.view)?.classList.add("active");renderAll()}));
function init(){const m=thisMonth();["dashboard-month","teacher-seat-month","calendar-month","attendance-month"].forEach(id=>{if($(id))$(id).value=m});bind();renderAll()}
function bind(){
$("dashboard-month")?.addEventListener("change",renderDashboard);$("teacher-seat-month")?.addEventListener("change",renderSeats);
$("add-seat-btn")?.addEventListener("click",()=>addSeatRow({seatNumber:document.querySelectorAll("#seat-table-body tr").length+1,name:"",className:"",id:"",password:"",canCheckAttendance:false}));
$("save-seat-config-btn")?.addEventListener("click",saveSeats);$("clear-seat-config-btn")?.addEventListener("click",()=>{if(confirm("선택한 월의 학생 배정을 모두 삭제할까요?")){const m=$("teacher-seat-month").value;state.monthlyStudents[m]=[];if(m===thisMonth())state.students=[];save();renderAll()}});
$("seat-import-file")?.addEventListener("change",importRoster);
$("calendar-month")?.addEventListener("change",renderCalendar);$("generate-month-btn")?.addEventListener("click",generateMonth);$("add-period-btn")?.addEventListener("click",()=>{state.periods.push({key:"p"+Date.now(),label:"추가 교시"});save();renderCalendar()});
$("attendance-month")?.addEventListener("change",renderAttendanceDates);$("attendance-date")?.addEventListener("change",renderAttendance);
$("auto-absence-on-approval")?.addEventListener("change",e=>{state.autoAbsenceOnApproval=e.target.value==="true";save();renderRequests()});
document.querySelectorAll(".dashboard-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".dashboard-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".dashboard-panel").forEach(x=>x.classList.remove("active"));$("dashboard-panel-"+b.dataset.dashboardView)?.classList.add("active")}));
}
function renderAll(){state=load();renderDashboard();renderSeats();renderCalendar();renderAttendanceDates();renderRequests();updateHero()}
function updateHero(){const m=thisMonth();$("hero-operating-days").textContent=Object.keys(state.attendanceRecords[m]||{}).length+"일";$("hero-pending-count").textContent=state.absenceRequests.filter(r=>r.status==="pending").length+"건"}
function renderDashboard(){const m=$("dashboard-month")?.value||thisMonth(),ss=studentsFor(m),days=Object.keys(state.attendanceRecords[m]||{}).length,abs=ss.reduce((n,s)=>n+monthAbsence(m,s.id),0);$("dashboard-summary").innerHTML=[["학생",ss.length+"명"],["운영일",days+"일"],["불참",abs+"회"],["승인 대기",state.absenceRequests.filter(r=>r.status==="pending"&&r.date.startsWith(m)).length+"건"]].map(([a,b])=>`<div class="stat-card"><p class="stat-label">${a}</p><p class="stat-value">${b}</p></div>`).join("");
const rows=ss.map(s=>({s,a:monthAbsence(m,s.id),p:monthParticipation(m,s.id)}));$("dashboard-seat-grid").innerHTML=rows.map(x=>`<button class="dashboard-seat-card" data-student="${esc(x.s.id)}"><span class="dashboard-seat-no">${x.s.seatNumber}번</span><p class="dashboard-seat-name">${esc(x.s.name)}</p><p class="dashboard-seat-meta">${esc(x.s.className||"")}</p><span class="mini-badge">불참 ${x.a}</span><span class="mini-badge">참여 ${x.p}</span></button>`).join("")||'<div class="empty-state">학생 정보가 없습니다.</div>';
const rank=(arr,key,label)=>arr.sort((a,b)=>b[key]-a[key]).map((x,i)=>`<button class="ranking-item" data-student="${esc(x.s.id)}"><span class="ranking-rank">${i+1}</span><span><span class="ranking-name">${esc(x.s.name)}</span><br><span class="ranking-meta">${esc(x.s.className||"")}</span></span><strong>${x[key]}${label}</strong></button>`).join("");
$("dashboard-absence-ranking").innerHTML=rank([...rows],"a","회")||'<div class="empty-state">집계할 데이터가 없습니다.</div>';$("dashboard-participation-ranking").innerHTML=rank([...rows],"p","회")||'<div class="empty-state">집계할 데이터가 없습니다.</div>';
$("dashboard-student-summary").innerHTML=rows.map(x=>`<tr><td>${x.s.seatNumber}</td><td>${esc(x.s.name)}</td><td>${esc(x.s.id)}</td><td>${x.a}</td><td>${x.p}</td></tr>`).join("");
}
function renderSeats(){const m=$("teacher-seat-month")?.value||thisMonth();$("teacher-name").value=state.teacherName||"";$("seat-table-body").innerHTML="";studentsFor(m).forEach(addSeatRow)}
function addSeatRow(s){const t=$("seat-row-template").content.cloneNode(true),r=t.querySelector("tr");r.querySelector(".seat-number-input").value=s.seatNumber||"";r.querySelector(".student-name-input").value=s.name||"";r.querySelector(".student-class-input").value=s.className||"";r.querySelector(".student-id-input").value=s.id||"";r.querySelector(".student-password-input").value=s.password||"";r.querySelector(".attendance-checker-input").checked=!!s.canCheckAttendance;r.querySelector(".remove-seat-btn").onclick=()=>r.remove();$("seat-table-body").appendChild(t)}
function collectRows(){return [...document.querySelectorAll("#seat-table-body tr")].map((r,i)=>({seatNumber:Number(r.querySelector(".seat-number-input").value)||i+1,name:r.querySelector(".student-name-input").value.trim(),className:r.querySelector(".student-class-input").value.trim(),canCheckAttendance:r.querySelector(".attendance-checker-input").checked,id:r.querySelector(".student-id-input").value.trim()||"student"+String(i+1).padStart(2,"0"),password:r.querySelector(".student-password-input").value.trim()||String(Math.floor(1000+Math.random()*9000))})).filter(s=>s.name).sort((a,b)=>a.seatNumber-b.seatNumber)}
function saveSeats(){const m=$("teacher-seat-month").value,ss=collectRows();const ids=ss.map(s=>s.id);if(new Set(ids).size!==ids.length)return alert("학생 아이디가 중복되었습니다.");state.teacherName=$("teacher-name").value.trim()||"정독실 담당교사";state.monthlyStudents[m]=ss;state.monthlyStudentMeta[m]={initialized:true,setupMode:"saved"};if(m===thisMonth()||!state.students.length)state.students=clone(ss);save();alert("저장했습니다.");renderAll()}
async function importRoster(e){const f=e.target.files?.[0];if(!f)return;try{const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{header:1,defval:""});$("seat-table-body").innerHTML="";data.slice(1).filter(r=>r.some(x=>String(x).trim())).forEach((r,i)=>addSeatRow({seatNumber:Number(r[0])||i+1,name:String(r[1]||"").trim(),className:String(r[2]||"").trim(),canCheckAttendance:/^(예|y|yes|true|1)$/i.test(String(r[3]).trim()),id:String(r[4]||"").trim(),password:String(r[5]||"").trim()}))}catch(err){alert("파일을 읽지 못했습니다.")}finally{e.target.value=""}}
function renderCalendar(){const m=$("calendar-month")?.value||thisMonth(),cfg=state.monthlyConfigs[m]||{activeWeekdays:[1,2,3,4,5],excludedWeekdays:[0,6],manualExcludedDates:[],notes:""};state.periods=state.periods?.length?state.periods:clone(DEFAULT_PERIODS);const labels=["일","월","화","수","목","금","토"];$("active-weekday-grid").innerHTML=labels.map((x,i)=>`<button type="button" class="weekday-chip ${cfg.activeWeekdays.includes(i)?"active":""}" data-day="${i}">${x}</button>`).join("");$("excluded-weekday-grid").innerHTML=labels.map((x,i)=>`<button type="button" class="weekday-chip ${cfg.excludedWeekdays.includes(i)?"active":""}" data-day="${i}">${x}</button>`).join("");document.querySelectorAll("#active-weekday-grid .weekday-chip").forEach(b=>b.onclick=()=>{toggle(cfg.activeWeekdays,+b.dataset.day);state.monthlyConfigs[m]=cfg;save();renderCalendar()});document.querySelectorAll("#excluded-weekday-grid .weekday-chip").forEach(b=>b.onclick=()=>{toggle(cfg.excludedWeekdays,+b.dataset.day);state.monthlyConfigs[m]=cfg;save();renderCalendar()});$("manual-excluded-dates").value=(cfg.manualExcludedDates||[]).join(", ");$("calendar-notes").value=cfg.notes||"";$("period-editor").innerHTML=periods().map((p,i)=>`<div class="period-editor-row"><input data-i="${i}" value="${esc(p.label)}"><button class="danger-btn" data-rm="${i}" type="button">삭제</button></div>`).join("");document.querySelectorAll("#period-editor input").forEach(x=>x.onchange=()=>{state.periods[+x.dataset.i].label=x.value.trim()||"교시";save()});document.querySelectorAll("#period-editor [data-rm]").forEach(x=>x.onclick=()=>{if(state.periods.length<=1)return alert("교시는 1개 이상 필요합니다.");state.periods.splice(+x.dataset.rm,1);save();renderCalendar()});renderCalendarPreview(m)}
function toggle(a,v){const i=a.indexOf(v);i>=0?a.splice(i,1):a.push(v)}
function renderCalendarPreview(m){const ds=Object.keys(state.attendanceRecords[m]||{}).sort();$("calendar-preview").innerHTML=ds.map(d=>`<div class="preview-row"><span>${fmtDate(d)}</span><strong>운영</strong></div>`).join("")||'<div class="empty-state">아직 생성된 출석부가 없습니다.</div>'}
function generateMonth(){const m=$("calendar-month").value;if(!m)return;const old=state.monthlyConfigs[m]||{},active=[...document.querySelectorAll("#active-weekday-grid .active")].map(b=>+b.dataset.day),excluded=[...document.querySelectorAll("#excluded-weekday-grid .active")].map(b=>+b.dataset.day),manual=$("manual-excluded-dates").value.split(",").map(x=>+x.trim()).filter(Boolean),cfg={...old,activeWeekdays:active,excludedWeekdays:excluded,manualExcludedDates:manual,notes:$("calendar-notes").value};state.monthlyConfigs[m]=cfg;const [y,mo]=m.split("-").map(Number),last=new Date(y,mo,0).getDate(),ss=studentsFor(m),rec={};for(let d=1;d<=last;d++){const dt=new Date(y,mo-1,d),wd=dt.getDay();if(!active.includes(wd)||excluded.includes(wd)||manual.includes(d))continue;const key=`${m}-${String(d).padStart(2,"0")}`,prev=state.attendanceRecords[m]?.[key],periodStatuses={},remarks={};ss.forEach(s=>{periodStatuses[s.id]=prev?.periodStatuses?.[s.id]||Object.fromEntries(periods().map(p=>[p.key,"present"]));remarks[s.id]=prev?.remarks?.[s.id]||""});rec[key]={date:key,periodStatuses,remarks}}state.attendanceRecords[m]=rec;save();alert("출석부를 생성했습니다.");renderAll()}
function renderAttendanceDates(){const m=$("attendance-month")?.value||thisMonth(),ds=Object.keys(state.attendanceRecords[m]||{}).sort();$("attendance-date").innerHTML=ds.map(d=>`<option value="${d}">${fmtDate(d)}</option>`).join("");if(ds.includes(today()))$("attendance-date").value=today();renderAttendance()}
function renderAttendance(){const m=$("attendance-month")?.value||thisMonth(),d=$("attendance-date")?.value,r=state.attendanceRecords[m]?.[d],ss=studentsFor(m);$("attendance-day-summary").innerHTML=r?`<span class="attendance-badge">${fmtDate(d)}</span><span class="attendance-badge">학생 ${ss.length}명</span>`:"";$("attendance-seat-grid").innerHTML=!r?'<div class="empty-state">출석부를 먼저 생성해 주세요.</div>':ss.map(s=>{const sm=statusMap(r,s.id);return `<article class="seat-card"><div class="seat-header-bar"><span class="seat-number">${s.seatNumber}번</span><span class="student-title">${esc(s.name)}</span></div><div class="period-grid">${periods().map(p=>`<div class="period-row"><span class="period-label">${esc(p.label)}</span><button class="period-btn ${sm[p.key]==="present"?"active present":""}" data-s="${esc(s.id)}" data-p="${p.key}" data-v="present">출석</button><button class="period-btn ${isAbsent(sm[p.key])?"active absent":""}" data-s="${esc(s.id)}" data-p="${p.key}" data-v="manual_absent">불참</button></div>`).join("")}</div><div class="remark-box">${esc(r.remarks?.[s.id]||"비고 없음")}</div></article>`}).join("");document.querySelectorAll("#attendance-seat-grid .period-btn").forEach(b=>b.onclick=()=>{const rr=state.attendanceRecords[m][d];rr.periodStatuses[b.dataset.s]=rr.periodStatuses[b.dataset.s]||{};if(rr.periodStatuses[b.dataset.s][b.dataset.p]==="approved_absent"&&b.dataset.v==="present")return;rr.periodStatuses[b.dataset.s][b.dataset.p]=b.dataset.v;save();renderAttendance();renderDashboard()})}
function renderRequests(){$("auto-absence-on-approval").value=String(state.autoAbsenceOnApproval!==false);$("request-table-body").innerHTML=[...state.absenceRequests].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(r=>{const s=student(r.studentId,r.date.slice(0,7))||{};return `<tr><td>${r.createdAt?new Date(r.createdAt).toLocaleDateString("ko-KR"):"-"}</td><td>${esc(s.name||r.studentId)}</td><td>${s.seatNumber||"-"}</td><td>${esc(r.date)}</td><td>${esc((r.periodKeys||[]).map(k=>periods().find(p=>p.key===k)?.label||k).join(", "))}</td><td>${esc(r.reason)}</td><td><span class="status-badge ${r.status}">${r.status==="pending"?"대기":r.status==="approved"?"승인":"반려"}</span></td><td>${r.status==="pending"?`<div class="request-actions"><button class="primary-btn" data-approve="${r.id}">승인</button><button class="danger-btn" data-reject="${r.id}">반려</button></div>`:"처리 완료"}</td></tr>`}).join("")||'<tr><td colspan="8">신청 내역이 없습니다.</td></tr>';document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>processReq(b.dataset.approve,"approved"));document.querySelectorAll("[data-reject]").forEach(b=>b.onclick=()=>processReq(b.dataset.reject,"rejected"))}
function processReq(id,status){const r=state.absenceRequests.find(x=>x.id===id);if(!r)return;r.status=status;r.processedAt=new Date().toISOString();if(status==="approved"&&state.autoAbsenceOnApproval!==false){const m=r.date.slice(0,7),rec=state.attendanceRecords[m]?.[r.date];if(rec){rec.periodStatuses[r.studentId]=rec.periodStatuses[r.studentId]||{};(r.periodKeys||[]).forEach(k=>rec.periodStatuses[r.studentId][k]="approved_absent");rec.remarks=rec.remarks||{};rec.remarks[r.studentId]="[승인 불참] "+r.reason}}save();renderAll()}
init();