const STORAGE_KEY="study-room-attendance-v1";
const DEFAULT_PERIODS=[{key:"period8",label:"8교시"},{key:"night1",label:"야자1교시"},{key:"night2",label:"야자2교시"}];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),monthNow=()=>today().slice(0,7);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let state={students:[],monthlyStudents:{},attendanceRecords:{},absenceRequests:[],periods:clone(DEFAULT_PERIODS),autoAbsenceOnApproval:true},currentStudentId=null;
function load(){const s=readSharedStateSync(STORAGE_KEY);if(s)state={...state,...s,students:s.students||[],monthlyStudents:s.monthlyStudents||{},attendanceRecords:s.attendanceRecords||{},absenceRequests:s.absenceRequests||[],periods:s.periods?.length?s.periods:clone(DEFAULT_PERIODS)}}
function periods(){return state.periods?.length?state.periods:DEFAULT_PERIODS}
function studentsFor(m){return Object.prototype.hasOwnProperty.call(state.monthlyStudents||{},m)?state.monthlyStudents[m]||[]:state.students||[]}
function me(m){return studentsFor(m||monthNow()).find(s=>s.id===currentStudentId)||state.students.find(s=>s.id===currentStudentId)||Object.values(state.monthlyStudents||{}).flat().find(s=>s.id===currentStudentId)}
function assigned(m){return studentsFor(m).some(s=>s.id===currentStudentId)}
function statusMap(r,id){const cur=r?.periodStatuses?.[id]||{},o={};periods().forEach(p=>o[p.key]=cur[p.key]||"present");return o}
function absent(v){return v==="manual_absent"||v==="approved_absent"}
function absenceCount(m){return Object.values(state.attendanceRecords[m]||{}).reduce((n,r)=>n+Object.values(statusMap(r,currentStudentId)).filter(absent).length,0)}
function participation(m){return Object.values(state.attendanceRecords[m]||{}).reduce((n,r)=>n+Object.values(statusMap(r,currentStudentId)).filter(v=>v==="present").length,0)}
function save(){writeSharedStateSync(STORAGE_KEY,state);load()}
function init(){$("student-page-month").value=monthNow();$("student-page-login-form").addEventListener("submit",login);$("student-page-logout-btn").addEventListener("click",logout);$("student-page-request-form").addEventListener("submit",submitRequest);$("student-page-month").addEventListener("change",render);if(localStorage.getItem(STUDENT_TOKEN_KEY)){load();const first=state.students?.[0]||Object.values(state.monthlyStudents||{}).flat()[0];if(first)currentStudentId=first.id}renderLogin()}
function login(e){e.preventDefault();const res=studentLoginSync($("student-page-login-id").value.trim(),$("student-page-login-password").value.trim());if(!res)return alert("아이디 또는 비밀번호가 올바르지 않습니다.");state=res.state;currentStudentId=res.student?.id||state.students?.[0]?.id;$("student-page-login-form").reset();renderLogin()}
function logout(){logoutSharedSession("student");currentStudentId=null;state={students:[],monthlyStudents:{},attendanceRecords:{},absenceRequests:[],periods:clone(DEFAULT_PERIODS),autoAbsenceOnApproval:true};renderLogin()}
function renderLogin(){const s=currentStudentId?me(monthNow()):null;$("student-login-panel").classList.toggle("hidden",!!s);$("student-page-session").classList.toggle("hidden",!s);if(s)render();else{$("student-page-history-body").innerHTML="";$("student-page-summary").innerHTML="";$("student-page-attendance-panel").classList.add("hidden")}}
function render(){load();const m=$("student-page-month").value||monthNow(),s=me(m);if(!s){logout();return}$("student-page-welcome").textContent=`${s.className?s.className+" ":""}${s.name} 대시보드${assigned(m)?"":" (이번 달 미배정)"}`;const req=state.absenceRequests.filter(r=>r.studentId===currentStudentId&&r.date.startsWith(m));$("student-page-summary").innerHTML=[["이번 달 미참여",absenceCount(m)+"회"],["이번 달 참여",participation(m)+"회"],["대기 중 신청",req.filter(r=>r.status==="pending").length+"건"],["승인 완료",req.filter(r=>r.status==="approved").length+"건"]].map(([a,b])=>`<div class="stat-card"><p class="stat-label">${a}</p><p class="stat-value">${b}</p></div>`).join("");renderPeriods();renderHistory();renderAttendance()}
function renderPeriods(){$("student-page-period-picker").innerHTML=periods().map(p=>`<label class="student-period-chip"><input type="checkbox" value="${esc(p.key)}"><span>${esc(p.label)}</span></label>`).join("")}
function renderHistory(){const rows=state.absenceRequests.filter(r=>r.studentId===currentStudentId).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$("student-page-history-body").innerHTML=rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc((r.periodKeys||[]).map(k=>periods().find(p=>p.key===k)?.label||k).join(", "))}</td><td>${esc(r.reason)}</td><td><span class="status-badge ${r.status}">${r.status==="pending"?"대기":r.status==="approved"?"승인":"반려"}</span></td></tr>`).join("")||'<tr><td colspan="4">신청 내역이 없습니다.</td></tr>'}
function renderAttendance(){const s=me(monthNow()),can=!!s?.canCheckAttendance,rec=state.attendanceRecords[monthNow()]?.[today()],roster=studentsFor(monthNow());$("student-page-attendance-panel").classList.toggle("hidden",!can);if(!can)return;$("student-page-attendance-meta").innerHTML=`<div class="attendance-summary"><span class="attendance-badge">${today()}</span><span class="attendance-badge">대상 학생 ${roster.length}명</span></div><p class="student-attendance-note">오늘 날짜 출석부만 체크할 수 있습니다.</p>`;if(!rec){$("student-page-attendance-grid").innerHTML='<div class="empty-state">오늘 날짜 출석부가 아직 생성되지 않았습니다.</div>';return}$("student-page-attendance-grid").innerHTML=roster.map(t=>{const sm=statusMap(rec,t.id);return `<article class="seat-card"><div class="seat-header-bar"><span class="seat-number">${t.seatNumber}번</span><span class="student-title">${esc(t.name)}</span></div><div class="period-grid">${periods().map(p=>`<div class="period-row"><span class="period-label">${esc(p.label)}</span><button class="period-btn ${sm[p.key]==="present"?"active present":""}" data-s="${esc(t.id)}" data-p="${p.key}" data-v="present">출석</button><button class="period-btn ${absent(sm[p.key])?"active absent":""}" data-s="${esc(t.id)}" data-p="${p.key}" data-v="manual_absent">불참</button></div>`).join("")}</div><div class="remark-box">${esc(rec.remarks?.[t.id]||"비고 없음")}</div></article>`}).join("");document.querySelectorAll("#student-page-attendance-grid .period-btn").forEach(b=>b.onclick=()=>{const r=state.attendanceRecords[monthNow()][today()];r.periodStatuses=r.periodStatuses||{};r.periodStatuses[b.dataset.s]=r.periodStatuses[b.dataset.s]||{};if(r.periodStatuses[b.dataset.s][b.dataset.p]==="approved_absent"&&b.dataset.v==="present")return;r.periodStatuses[b.dataset.s][b.dataset.p]=b.dataset.v;save();render()})}
function submitRequest(e){e.preventDefault();const s=me(),date=$("student-page-request-date").value,reason=$("student-page-request-reason").value.trim(),keys=[...document.querySelectorAll("#student-page-period-picker input:checked")].map(x=>x.value);if(!s||!date||!reason||!keys.length)return alert("날짜, 불참 교시, 사유를 모두 입력해 주세요.");const m=date.slice(0,7);if(!assigned(m))return alert("선택한 달에는 현재 학생이 배정되어 있지 않습니다.");if(!state.attendanceRecords[m]?.[date])return alert("해당 날짜는 운영일이 아니거나 아직 출석부가 생성되지 않았습니다.");state.absenceRequests.push({id:crypto.randomUUID?.()||Date.now()+"",studentId:currentStudentId,date,periodKeys:keys,reason,status:"pending",createdAt:new Date().toISOString()});save();$("student-page-request-form").reset();render();alert("불참 신청이 제출되었습니다.")}
init();